import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { adminChatId } from "../toolkit/index.js";
import { createOrder, getUser, saveProfile, validPhone } from "../store.js";
import { cartText, force } from "../storefront.js";
import { inlineKeyboard, inlineButton } from "../toolkit/index.js";
const composer = new Composer<Ctx>();
function ask(ctx: Ctx) { const f = ctx.session.flow; if (!f || (f.kind !== "checkout" && f.kind !== "profile")) return; if (f.step === "name") return ctx.reply("Введите имя для доставки.", { reply_markup: force("Имя и фамилия") }); if (f.step === "phone") return ctx.reply("Введите номер телефона.", { reply_markup: force("+7 900 000-00-00") }); return ctx.reply("Введите адрес доставки.", { reply_markup: force("Город, улица, дом") }); }
composer.callbackQuery("checkout:start", async (ctx) => { await ctx.answerCallbackQuery(); const { rows } = await cartText(ctx); if (!rows.length) { await ctx.reply("Корзина пуста. Откройте каталог, чтобы выбрать товары."); return; } const u = await getUser(ctx); if (u.profile) { ctx.session.flow = { kind: "checkout", step: "address", values: { ...u.profile } }; await ctx.reply(`Доставка\nИмя: ${u.profile.name}\nТелефон: ${u.profile.phone}\nАдрес: ${u.profile.address}\n\nПодтвердить эти данные?`, { reply_markup: inlineKeyboard([[inlineButton("Подтвердить", "checkout:shipping:confirm"), inlineButton("Изменить", "checkout:edit")]]) }); } else { ctx.session.flow = { kind: "checkout", step: "name", values: {} }; await ask(ctx); } });
composer.callbackQuery("checkout:edit", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.flow = { kind: "checkout", step: "name", values: {} }; await ask(ctx); });
composer.callbackQuery("checkout:shipping:confirm", async (ctx) => { await ctx.answerCallbackQuery(); await ctx.reply("Выберите способ оплаты.", { reply_markup: inlineKeyboard([[inlineButton("При получении", "checkout:payment:cod"), inlineButton("По счёту", "checkout:payment:invoice")]]) }); });
composer.callbackQuery(/^checkout:payment:(cod|invoice)$/, async (ctx) => { await ctx.answerCallbackQuery(); const f = ctx.session.flow; if (!f || f.kind !== "checkout" || !f.values.name || !f.values.phone || !f.values.address) { await ctx.reply("Данные доставки не заполнены. Начните оформление заново."); return; } const result = await createOrder(ctx, f.values as { name: string; phone: string; address: string }); ctx.session.flow = undefined; if ("error" in result) { await ctx.reply(result.error === "stock" ? "Некоторых товаров уже нет в нужном количестве." : "Корзина пуста."); return; } const o = result.order; await ctx.reply(`Заказ ${o.id} создан.\nСумма: ${o.total.toFixed(2)} ${o.currency}\nСтатус оплаты: ожидает оплаты.\nМы свяжемся с вами для подтверждения и оплаты.`, { reply_markup: inlineKeyboard([[inlineButton("Мои заказы", "orders:mine")]]) }); const owner = adminChatId(ctx as unknown as { env?: Record<string, unknown> }); if (owner) { try { await ctx.api.sendMessage(owner, `Новый заказ ${o.id}\nКлиент: ${o.shipping.name}\nТелефон: ${o.shipping.phone}\nАдрес: ${o.shipping.address}\n${o.items.map((x) => `${x.title} × ${x.quantity} · ${x.price * x.quantity} ${x.currency}`).join("\n")}\nИтого: ${o.total} ${o.currency}`, { reply_markup: inlineKeyboard([[inlineButton("Выполнен", `admin:order:fulfilled:${o.id}`), inlineButton("Отменён", `admin:order:cancelled:${o.id}`)]]) }); } catch { /* A blocked owner must not break the customer's order */ } } });
composer.on("message:text", async (ctx, next) => { const f = ctx.session.flow; if (!f || (f.kind !== "checkout" && f.kind !== "profile")) return next(); const value = ctx.message.text.trim(); if (f.step === "name") { if (value.length < 2 || value.length > 80) { await ctx.reply("Введите имя от 2 до 80 символов."); return; } f.values.name = value; f.step = "phone"; await ask(ctx); return; } if (f.step === "phone") { if (!validPhone(value)) { await ctx.reply("Введите корректный номер телефона."); return; } f.values.phone = value; f.step = "address"; await ask(ctx); return; } if (value.length < 5 || value.length > 200) { await ctx.reply("Введите полный адрес доставки."); return; } f.values.address = value; if (f.kind === "profile") { await saveProfile(ctx, f.values as { name: string; phone: string; address: string }); ctx.session.flow = undefined; await ctx.reply("Профиль сохранён."); } else { await ctx.reply(`Доставка\nИмя: ${f.values.name}\nТелефон: ${f.values.phone}\nАдрес: ${f.values.address}\n\nПодтвердить эти данные?`, { reply_markup: inlineKeyboard([[inlineButton("Подтвердить", "checkout:shipping:confirm"), inlineButton("Изменить", "checkout:edit")]]) }); } });
export default composer;
