import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { adminChatId, requireOwner } from "../toolkit/index.js";
import { addProduct, findProduct, now, removeProduct, resetMetrics, setOrderStatus, setStock, snapshot, updateProduct, type Product } from "../store.js";
import { force } from "../storefront.js";
const composer = new Composer<Ctx>();
const gate = (ctx: Ctx) => requireOwner(ctx as unknown as Parameters<typeof requireOwner>[0]);
function productPrompt(ctx: Ctx) { const f = ctx.session.flow; if (!f || f.kind !== "product") return; const labels: Record<string, string> = { title: "Введите название товара.", description: "Введите описание товара.", price: "Введите цену числом.", currency: "Введите валюту, например RUB.", photo: "Отправьте URL фото или напишите пропустить.", stock: "Введите количество на складе целым числом." }; return ctx.reply(labels[f.step], { reply_markup: force(f.step) }); }
async function list(ctx: Ctx) { const s = await snapshot(); await ctx.reply(s.products.length ? `Товары\n\n${s.products.map((p) => `${p.id} · ${p.title}\n${p.price} ${p.currency} · остаток ${p.stock}`).join("\n\n")}` : "Каталог пуст."); }
composer.command("addproduct", async (ctx) => { if (!(await gate(ctx))) return; ctx.session.flow = { kind: "product", step: "title", values: {} }; await productPrompt(ctx); });
composer.command("editproduct", async (ctx) => { if (!(await gate(ctx))) return; const id = ctx.match.trim(); const p = findProduct(await snapshot(), id); if (!p) { await ctx.reply("Товар не найден."); return; } ctx.session.flow = { kind: "product", id, step: "title", values: { ...p } }; await ctx.reply("Введите новое название товара или напишите пропустить.", { reply_markup: force("Название") }); });
composer.command("removeproduct", async (ctx) => { if (!(await gate(ctx))) return; const id = ctx.match.trim(); const p = findProduct(await snapshot(), id); if (!p) { await ctx.reply("Товар не найден."); return; } await removeProduct(id); await ctx.reply(`Товар «${p.title}» удалён из каталога.`); });
composer.command("listproducts", async (ctx) => { if (!(await gate(ctx))) return; await list(ctx); });
composer.command("stock", async (ctx) => { if (!(await gate(ctx))) return; const [id, raw] = ctx.match.trim().split(/\s+/); const qty = Number(raw); if (!id || !Number.isInteger(qty) || qty < 0) { await ctx.reply("Используйте: /stock ID количество"); return; } const p = await setStock(id, qty); await ctx.reply(p ? `Остаток товара обновлён: ${qty} шт.` : "Товар не найден."); });
composer.command("order", async (ctx) => { if (!(await gate(ctx))) return; const id = ctx.match.trim(); const o = (await snapshot()).orders.find((x) => x.id === id); if (!o) { await ctx.reply("Заказ не найден."); return; } await ctx.reply(`${o.id}\n${o.shipping.name}\n${o.shipping.phone}\n${o.shipping.address}\n${o.items.map((x) => `${x.title} × ${x.quantity}`).join("\n")}\nИтого: ${o.total} ${o.currency}\nСтатус: ${o.status}`); });
composer.command("orders_export", async (ctx) => { if (!(await gate(ctx))) return; const s = await snapshot(); const csv = ["order_id,status,created_at,total,currency", ...s.orders.map((o) => `${o.id},${o.status},${new Date(o.createdAt).toISOString()},${o.total},${o.currency}`)].join("\n"); await ctx.reply(csv); });
composer.command("metrics", async (ctx) => { if (!(await gate(ctx))) return; const s = await snapshot(); const active = Object.values(s.users).filter((u) => now() - u.activeAt < 30 * 86400000).length; const top = Object.entries(s.productSales).sort((a, b) => b[1].quantity - a[1].quantity).slice(0, 10).map(([id, x]) => `${findProduct(s, id)?.title ?? id}: ${x.quantity} шт. / ${x.revenue}`).join("\n") || "Продаж пока нет."; const text = `Метрики магазина\nАктивных пользователей: ${active}\nЗаказов: ${s.orders.length}\nТоп товаров:\n${top}`; const target = adminChatId(ctx as unknown as { env?: Record<string, unknown> }); if (target && target !== String(ctx.chat?.id)) await ctx.api.sendMessage(target, text); else await ctx.reply(text, { reply_markup: { inline_keyboard: [[{ text: "Сбросить метрики", callback_data: "admin:metrics:reset" }]] } }); });
composer.callbackQuery("admin:metrics:reset", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; await resetMetrics(); await ctx.reply("Метрики продаж сброшены."); });
composer.command("dashboard", async (ctx) => { if (!(await gate(ctx))) return; await ctx.reply("Откройте /metrics, чтобы получить текущие метрики магазина."); });
composer.callbackQuery(/^admin:order:(fulfilled|cancelled):(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const o = await setOrderStatus(ctx.match[2], ctx.match[1] === "fulfilled" ? "fulfilled" : "cancelled"); await ctx.reply(o ? `Заказ ${o.id}: статус обновлён.` : "Заказ не найден."); });
composer.on("message:text", async (ctx, next) => { const f = ctx.session.flow; if (!f || f.kind !== "product") return next(); if (!(await gate(ctx))) return; const value = ctx.message.text.trim(); if (f.step === "title") { if (value.toLowerCase() !== "пропустить") f.values.title = value; if (!f.values.title) { await ctx.reply("Название не может быть пустым."); return; } f.step = "description"; await productPrompt(ctx); return; } if (f.step === "description") { if (value.toLowerCase() !== "пропустить") f.values.description = value; if (!f.values.description) { await ctx.reply("Описание не может быть пустым."); return; } f.step = "price"; await productPrompt(ctx); return; } if (f.step === "price") { const price = Number(value.replace(",", ".")); if (!Number.isFinite(price) || price < 0) { await ctx.reply("Введите неотрицательную цену числом."); return; } f.values.price = price; f.step = "currency"; await productPrompt(ctx); return; } if (f.step === "currency") { if (!/^[A-Za-z]{3}$/.test(value)) { await ctx.reply("Введите трёхбуквенную валюту, например RUB."); return; } f.values.currency = value.toUpperCase(); f.step = "photo"; await productPrompt(ctx); return; } if (f.step === "photo") { if (value.toLowerCase() !== "пропустить") f.values.photo = value; f.step = "stock"; await productPrompt(ctx); return; } const stock = Number(value); if (!Number.isInteger(stock) || stock < 0) { await ctx.reply("Введите количество целым неотрицательным числом."); return; } f.values.stock = stock; const saved = f.id ? await updateProduct(f.id, f.values) : await addProduct(f.values as Omit<Product, "id">); ctx.session.flow = undefined; await ctx.reply(`Товар сохранён: ${saved?.id ?? "готово"}.`); });
export default composer;
