import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { registerMainMenuItem, inlineButton, inlineKeyboard } from "../toolkit/index.js";
import { getUser } from "../store.js";
import { force } from "../storefront.js";
registerMainMenuItem({ label: "Профиль", data: "profile:open", order: 40 });
const composer = new Composer<Ctx>();
composer.callbackQuery("profile:open", async (ctx) => { await ctx.answerCallbackQuery(); const u = await getUser(ctx); const p = u.profile; await ctx.reply(p ? `Профиль\nИмя: ${p.name}\nТелефон: ${p.phone}\nАдрес: ${p.address}` : "Профиль пока не заполнен.", { reply_markup: inlineKeyboard([[inlineButton("Изменить профиль", "profile:edit")], [inlineButton("Главное меню", "menu:main")]]) }); });
composer.callbackQuery("profile:edit", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.flow = { kind: "profile", step: "name", values: {} }; await ctx.reply("Введите имя для профиля.", { reply_markup: force("Имя и фамилия") }); });
export default composer;
