import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { registerMainMenuItem, inlineButton, inlineKeyboard } from "../toolkit/index.js";
import { getProfile, updateProfile } from "../store.js";
import { force } from "../storefront.js";
import { evaluateUserAlerts, sendMorningSummary } from "./alerts.js";
registerMainMenuItem({ label: "Settings", data: "user:settings", order: 40 });
const composer = new Composer<Ctx>();
function keyboard() { return inlineKeyboard([[inlineButton("Timezone", "settings:timezone"), inlineButton("Quiet hours", "settings:quiet")], [inlineButton("Morning summary", "settings:summary"), inlineButton("Alert cooldown", "settings:cooldown")], [inlineButton("Check alerts", "alerts:check"), inlineButton("Send summary", "summary:send")], [inlineButton("Back to menu", "menu:main")]]); }
composer.callbackQuery("user:settings", async (ctx) => { await ctx.answerCallbackQuery(); const p = await getProfile(ctx); await ctx.reply(`Settings\nTimezone: ${p.timezone}\nQuiet hours: ${p.quietStart && p.quietEnd ? `${p.quietStart}–${p.quietEnd}` : "off"}\nMorning summary: ${p.morning ? p.summaryTime ?? "enabled" : "off"}\nAlert cooldown: ${p.cooldown} hours`, { reply_markup: keyboard() }); });
composer.callbackQuery("settings:timezone", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.flow = { kind: "settings", step: "timezone" }; await ctx.reply("Enter your IANA timezone, such as Europe/London.", { reply_markup: force("Timezone") }); });
composer.callbackQuery("settings:quiet", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.flow = { kind: "settings", step: "quiet" }; await ctx.reply("Enter quiet hours as HH:MM-HH:MM, or off.", { reply_markup: force("22:00-07:00") }); });
composer.callbackQuery("settings:summary", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.flow = { kind: "settings", step: "summary" }; await ctx.reply("Enter the morning summary time as HH:MM, or off.", { reply_markup: force("08:00") }); });
composer.callbackQuery("settings:cooldown", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.flow = { kind: "settings", step: "cooldown" }; await ctx.reply("Enter the alert cooldown in hours, from 1 to 168.", { reply_markup: force("6") }); });
composer.callbackQuery("alerts:check", async (ctx) => { await ctx.answerCallbackQuery(); await evaluateUserAlerts(ctx); await ctx.reply("Alerts checked.", { reply_markup: keyboard() }); });
composer.callbackQuery("summary:send", async (ctx) => { await ctx.answerCallbackQuery(); const sent = await sendMorningSummary(ctx); if (!sent) await ctx.reply("There are no queued alerts for your morning summary.", { reply_markup: keyboard() }); });
composer.on("message:text", async (ctx, next) => { const f = ctx.session.flow; if (!f || f.kind !== "settings") return next(); const v = ctx.message.text.trim(); if (f.step === "timezone") { try { new Intl.DateTimeFormat("en", { timeZone: v }); } catch { await ctx.reply("I couldn't find that timezone. Try an IANA name such as Europe/London."); return; } await updateProfile(ctx, { timezone: v }); } else if (f.step === "quiet") { if (v.toLowerCase() === "off") await updateProfile(ctx, { quietStart: undefined, quietEnd: undefined }); else if (!/^([01]\d|2[0-3]):[0-5]\d-([01]\d|2[0-3]):[0-5]\d$/.test(v)) { await ctx.reply("Use HH:MM-HH:MM, for example 22:00-07:00."); return; } else { const [quietStart, quietEnd] = v.split("-"); await updateProfile(ctx, { quietStart, quietEnd }); } } else if (f.step === "summary") { if (v.toLowerCase() === "off") await updateProfile(ctx, { morning: false, summaryTime: undefined }); else if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(v)) { await ctx.reply("Use a time like 08:00, or off."); return; } else await updateProfile(ctx, { morning: true, summaryTime: v }); } else { const n = Number(v); if (!Number.isInteger(n) || n < 1 || n > 168) { await ctx.reply("Enter a whole number from 1 to 168."); return; } await updateProfile(ctx, { cooldown: n }); } ctx.session.flow = undefined; await ctx.reply("Settings saved.", { reply_markup: keyboard() }); });
export default composer;
