import type { Ctx } from "./bot.js";
import { inlineButton, inlineKeyboard } from "./toolkit/index.js";
import { findProduct, getUser, money, snapshot, type Product, type StoreState } from "./store.js";

export const back = inlineKeyboard([[inlineButton("Главное меню", "menu:main")]]);
export function menu() { return inlineKeyboard([[inlineButton("Каталог", "catalog:open"), inlineButton("Корзина", "cart:open")], [inlineButton("Заказы", "orders:mine"), inlineButton("Профиль", "profile:open")], [inlineButton("Помощь", "menu:help")]]); }
export function productButtons(p: Product) { return inlineKeyboard([[inlineButton("Добавить в корзину", `cart:add:${p.id}`)], [inlineButton("Назад к каталогу", "catalog:open")]]); }
export async function catalogText(page = 0) { const s = await snapshot(); const products = s.products.slice(page * 5, page * 5 + 5); return { s, products, page, pages: Math.max(1, Math.ceil(s.products.length / 5)) }; }
export function catalogMarkup(products: Product[], page: number, pages: number) { const rows = products.map((p) => [inlineButton(`${p.title} · ${money(p.price, p.currency)}`, `product:view:${p.id}`), inlineButton("В корзину", `cart:add:${p.id}`)]); if (page > 0 || page + 1 < pages) rows.push([...(page > 0 ? [inlineButton("Назад", `catalog:page:${page - 1}`)] : []), ...(page + 1 < pages ? [inlineButton("Далее", `catalog:page:${page + 1}`)] : [])]); rows.push([inlineButton("Главное меню", "menu:main")]); return inlineKeyboard(rows); }
export function productText(p: Product) { return `${p.title}\n\n${p.description}\n\nЦена: ${money(p.price, p.currency)}\nВ наличии: ${p.stock > 0 ? `${p.stock} шт.` : "нет"}${p.category ? `\nКатегория: ${p.category}` : ""}${p.photo ? `\nФото: ${p.photo}` : ""}`; }
export async function cartText(ctx: Ctx) { const s = await snapshot(); const u = await getUser(ctx); const rows = u.cart.map((line) => { const p = findProduct(s, line.productId); return p ? { p, quantity: line.quantity, subtotal: p.price * line.quantity } : undefined; }).filter((x): x is { p: Product; quantity: number; subtotal: number } => Boolean(x)); const total = rows.reduce((n, x) => n + x.subtotal, 0); return { s, u, rows, total }; }
export function cartMarkup(rows: Array<{ p: Product; quantity: number }>) { const buttons = rows.flatMap((x) => [[inlineButton(`− ${x.p.title}`, `cart:dec:${x.p.id}`), inlineButton(`${x.quantity} шт.`, `product:view:${x.p.id}`), inlineButton(`＋`, `cart:inc:${x.p.id}`)], [inlineButton("Удалить", `cart:remove:${x.p.id}`)]]); buttons.push([inlineButton("Оформить заказ", "checkout:start")], [inlineButton("Очистить корзину", "cart:clear")], [inlineButton("Назад", "menu:main")]); return inlineKeyboard(buttons); }
export function ordersText(s: StoreState, ids: string[]) { const orders = s.orders.filter((o) => ids.includes(o.id)).sort((a, b) => b.createdAt - a.createdAt); if (!orders.length) return "Заказов пока нет. Откройте каталог, чтобы выбрать товары."; return `Ваши заказы\n\n${orders.map((o) => `${o.id} · ${o.status === "new" ? "Новый" : o.status === "fulfilled" ? "Выполнен" : "Отменён"}\n${o.items.map((x) => `${x.title} × ${x.quantity}`).join(", ")}\nИтого: ${money(o.total, o.currency)}`).join("\n\n")}`; }
export function force(placeholder: string) { return { force_reply: true as const, input_field_placeholder: placeholder }; }
